name: Mirror Peerchan

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight (UTC)
  workflow_dispatch:  # Allow manual triggering

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clean workspace (ensure no conflicts)
        run: rm -rf source.git

      - name: Clone source repository
        run: git clone --mirror https://gitgud.io/threshold862543/peerchan.git source.git

      - name: Mirror to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          cd source.git
          git remote set-url --push origin https://x-access-token:${{ secrets.MY_PAT }}@github.com/peerchann/peerchan.git
          git push --mirror

      - name: Confirm success
        run: echo "Mirror operation completed successfully!"
